I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "game/script.rpy", line 269, in set_default
    default bedroom_menu1 = set()
Exception: store.bedroom_menu1 is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "C:\Users\nonot\Downloads\New folder (2)\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\nonot\Downloads\New folder (2)\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "C:\Users\nonot\Downloads\New folder (2)\renpy-8.0.3-sdk\renpy\exports.py", line 3797, in execute_default_statement
    i.set_default(start)
  File "game/script.rpy", line 269, in set_default
    default bedroom_menu1 = set()
Exception: store.bedroom_menu1 is being given a default a second time.

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.3.22090809
project_YouJustWokeUp 1.0
Mon Oct 31 21:59:32 2022
